// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL9ee0Zacnw3DZUUQ3mk4sFgvVIaH5qV0',
    appId: '1:353659744611:web:ba783ed1179a36154be356',
    messagingSenderId: '353659744611',
    projectId: 'servicepay-68b17',
    authDomain: 'servicepay-68b17.firebaseapp.com',
    storageBucket: 'servicepay-68b17.firebasestorage.app',
    measurementId: 'G-ZZJ3ZZFXHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS0SvpTtgw6fvzACt_90g2XYQZ93ErHjk',
    appId: '1:353659744611:android:8ad1d6235be3e6524be356',
    messagingSenderId: '353659744611',
    projectId: 'servicepay-68b17',
    storageBucket: 'servicepay-68b17.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_WVBY_Yn8MmvNighTf0-CakmOLCy0bJI',
    appId: '1:353659744611:ios:a6627efc0c3488904be356',
    messagingSenderId: '353659744611',
    projectId: 'servicepay-68b17',
    storageBucket: 'servicepay-68b17.firebasestorage.app',
    iosBundleId: 'com.example.servicepayApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_WVBY_Yn8MmvNighTf0-CakmOLCy0bJI',
    appId: '1:353659744611:ios:a6627efc0c3488904be356',
    messagingSenderId: '353659744611',
    projectId: 'servicepay-68b17',
    storageBucket: 'servicepay-68b17.firebasestorage.app',
    iosBundleId: 'com.example.servicepayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL9ee0Zacnw3DZUUQ3mk4sFgvVIaH5qV0',
    appId: '1:353659744611:web:396831b439ab96324be356',
    messagingSenderId: '353659744611',
    projectId: 'servicepay-68b17',
    authDomain: 'servicepay-68b17.firebaseapp.com',
    storageBucket: 'servicepay-68b17.firebasestorage.app',
    measurementId: 'G-YKTB2X0ST7',
  );
}
